### ISSUE TITLE
How to process two canonical images

### ISSUE THREAD

**Issue by wyz894272237** [qiuyu96/CoDeF#35]
Thank you for doing such a great job!

I want to use controlnet for video style migration. For your example beauty_1, the step of reconstruction generates two canonical images. If I simply use the controlnet to transfer these tow images, the generated video is bad even with a same controlnet seed. May I ask which step is wrong with me？

Thank you!

**Comment by ken-ouyang** [comment]
Can you show the canonical image, translated canonical image and the translated video? I cannot decide which step is wrong as the information is too limited.

**Comment by wyz894272237** [comment]
Thank you for your reply.

I follow the reconstruction step and get two canonical images like below.
![canonical_0](https://github.com/qiuyu96/CoDeF/assets/43692893/db8a612a-e5be-4c3e-8bf2-29a95094670c)
![canonical_1](https://github.com/qiuyu96/CoDeF/assets/43692893/26f448dd-752e-45f0-bb7f-947836273f75)
And then I use controlnet with the same seed to generate images like below.
![output_0](https://github.com/qiuyu96/CoDeF/assets/43692893/45dfa5ee-4dc4-45e6-a6c4-ea1f219a76cf)
![output_1](https://github.com/qiuyu96/CoDeF/assets/43692893/7af141fd-283a-40f6-b6b2-4314a83703b6)
The dual video is

https://github.com/qiuyu96/CoDeF/assets/43692893/26d5c5f2-cc3b-4f66-8790-5895f68106a3

I think it is due to the inconsistency between two generated images

**Comment by ken-ouyang** [comment]
The issue you're encountering is likely due to the translated image not being perfectly aligned with the original one. To address this, you might want to try the following solutions:
1. Consider using a model that promotes better alignment, such as a lineart or animelineart model. These models are explicitly designed to preserve the structure of the original image in the translated one and may offer improved alignment.
2. Another approach could be to focus solely on the foreground for inference. This can be achieved by setting the masks to null during the inference process.

**Comment by wyz894272237** [comment]
Thank you for your advice. I will try it.

**Comment by cslvjt** [comment]
Hello, may I know which model of ControlNet you are referring to？ Thank you.

**Comment by wyz894272237** [comment]
openpose
